[17.0] [MIG] survey_crm_generation
OCA/survey pull request #107
Opened 2024-01-17 19:33 UTC by Rad0van

Standard migration

2024-02-09 07:48 UTC, chienandalu commented
Please include https://github.com/OCA/survey/pull/100

2025-04-24 11:45 UTC, pilarvargas-tecnativa requested changes
cc @tecnativa TT51948

2025-04-24 11:45 UTC, pilarvargas-tecnativa commented on survey_crm_generation/views/crm_lead_views.xml
> +                    invisible="survey_user_input_id == False"
`invisible="not survey_user_input_id"`

2025-04-24 11:45 UTC, pilarvargas-tecnativa commented on survey_crm_generation/views/survey_survey_views.xml
> +                        invisible="generate_leads == False"
`invisible="not generate_leads"`

2025-04-24 11:45 UTC, pilarvargas-tecnativa commented on survey_crm_generation/views/survey_user_input_views.xml
> +                <field name="opportunity_id" invisible="opportunity_id == False" />
`invisible="not opportunity_id"`

2025-04-24 11:45 UTC, pilarvargas-tecnativa commented on survey_crm_generation/static/tests/survey_crm_generation_tour.js
> +odoo.define(
The tests do not have the correct structure. The js files in v17 should have the extension ‘.esm.js’ and have the tag ‘/** @odoo-module */’ in the header, also tours are now done in registry.category(‘web_tour.tours’). Please review the tours and adapt them to run in v17.

2025-04-24 13:55 UTC, Rad0van commented
@pilarvargas-tecnativa thanks for comments. Not sure how I could miss those and also how it could work. Currently not having time to work on this. If you need this done sooner feel free to take over.

2025-04-24 16:03 UTC, pilarvargas-tecnativa commented
You don't need to commit every change, just include it all in the migration commit.

2025-04-24 16:05 UTC, pilarvargas-tecnativa commented
> thanks for comments. Not sure how I could miss those and also how it could work. Currently not having time to work on this. If you need this done sooner feel free to take over.

Ok, if you prefer, I'll take care of the migration respecting your commit changes. Thanks

2025-04-24 16:11 UTC, Rad0van commented
> You don't need to commit every change, just include it all in the migration commit.

I know. Was just trying quick fix and obviously failed to see what the problem was. I'll squash the commits.

2025-04-25 11:48 UTC, pedrobaeza commented
@Rad0van are you fixing the CI?

2025-04-30 13:12 UTC, Rad0van commented
@pilarvargas-tecnativa @pedrobaeza should be fine now. I'll squash the commits as well.

2025-04-30 13:29 UTC, pedrobaeza commented
/ocabot migration survey_crm_generation

2025-04-30 13:36 UTC, Rad0van commented
Shall I include #100 as @chienandalu suggested? @pedrobaeza @pilarvargas-tecnativa

2025-04-30 13:38 UTC, pedrobaeza commented
Yes, please. Everything should be synced with latest 15.0.

2025-04-30 14:35 UTC, Rad0van commented
@pedrobaeza I have cherry-picked the commit and all the tests pass. Can I leave like this or should the commit be maybe squashed with the migration one?

2025-04-30 18:08 UTC, pedrobaeza commented
The idea is to put such commits before migration, and cherry-picking them, for preserving commit attribution.

2025-05-06 15:34 UTC, pilarvargas-tecnativa commented
superseded by #167

2025-05-06 16:00 UTC, pedrobaeza commented
We continue on the other PR, but without losing your attribution.

2025-05-06 16:00 UTC, closed without merging