[16.0][ADD] survey_resource_booking module
OCA/survey pull request #136
Opened 2024-11-20 14:18 UTC by arielbarreiros96

2024-11-20 14:28 UTC, pedrobaeza commented
Shouldn't it be resource_booking_survey instead? Which is the usual source? About the contributors, you don't need to put all the resource_booking ones, s this is a different module.

2024-11-20 14:45 UTC, Christian-RB commented
This is a Standard Migration of https://github.com/OCA/survey/tree/15.0/survey_resource_booking it had the wrong tag. Sorry for the confusion. He is working now on keeping the commit history.

2024-11-20 16:57 UTC, pedrobaeza commented
OK, then maybe we selected the name badly in the first place, hehe.

2024-11-21 11:07 UTC, rrebollo approved these changes
Code Review LGTM but I made some suggestions U might consider.

2024-11-21 11:07 UTC, rrebollo commented on survey_question_type_nps/i18n/it.po
This is coming from another addon. Should this be here?

2024-11-21 11:07 UTC, rrebollo commented on survey_resource_booking/models/resource_booking.py
> +                if not email_split(one.partner_id.email):
:+1:  to the use of email_split

2024-11-21 11:07 UTC, rrebollo commented on survey_resource_booking/tests/test_invite.py
> +from ...resource_booking.tests.common import create_test_data
why don't U use instead:
```suggestion
from odoo.addons.resource_booking.tests.common import create_test_data
```

2025-06-13 22:53 UTC, edescalona approved these changes
LGTM

2025-06-14 08:30 UTC, pedrobaeza requested changes
/ocabot migration survey_resource_booking

2025-06-14 08:30 UTC, pedrobaeza commented on survey_resource_booking/views/resource_booking_type_views.xml
> +    <record id="resource_booking_type_view_form" model="ir.ui.view">
Don't change XML-IDs to ease migration path.

2025-06-14 08:30 UTC, pedrobaeza commented on survey_resource_booking/tests/test_invite.py
> +from odoo.addons.resource_booking.tests.common import create_test_data
Why changing this?

2025-08-16 04:54 UTC, antoniodavid approved these changes
LGTM

2025-08-16 04:55 UTC, antoniodavid commented
ping @pedrobaeza

2025-08-16 09:47 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2025-08-16 09:54 UTC, merged