[16.0][ADD]survey_link_base
OCA/survey pull request #141
Opened 2024-12-30 12:53 UTC by adasatorres

Good morning, this addon creates a mixin and a wizard to enable the generation of surveys from other models.

2024-12-30 15:40 UTC, jorgeglez1990 approved these changes
Functional Review: LGTM.

2025-01-03 12:23 UTC, rrebollo approved these changes
Code Review LGTM! Consider my suggestions.

2025-01-03 12:23 UTC, rrebollo commented on survey_link_base/__manifest__.py
> +        generation of surveys from other models..""",
```suggestion
        generation of surveys from other models.""",
```

2025-01-03 12:23 UTC, rrebollo commented on survey_link_base/models/survey_link_mixin.py
> +        return False
is this intended for recordsets with multiple records or self.ensure_one()?

2025-01-03 12:23 UTC, rrebollo commented on survey_link_base/models/survey_link_mixin.py
> +        survey_link_wizard = self.env["survey.link.wizard"].create(
```suggestion
        self.ensure_one()
        survey_link_wizard = self.env["survey.link.wizard"].create(
```

2025-02-15 08:26 UTC, diggy128 commented
It seems runboat is stuck. Can someone retrigger the build?

2025-02-21 12:39 UTC, adasatorres commented on survey_link_base/models/survey_link_mixin.py
> +        survey_link_wizard = self.env["survey.link.wizard"].create(
@rrebollo Thx.

2025-02-21 12:39 UTC, adasatorres commented on survey_link_base/models/survey_link_mixin.py
> +        return False
Hi @rrebollo the default template is defined by company. I really don't think it's a concern whether there is a recordset or not. In any case, the methods where I use them have self.ensure_one().

2025-02-21 12:40 UTC, adasatorres commented on survey_link_base/__manifest__.py
> +        generation of surveys from other models..""",
@rrebollo Thx.

2025-05-28 11:16 UTC, diggy128 commented
Runboat seems stuck again. Can someone retrigger the build?

2025-05-28 11:26 UTC, diggy128 requested changes

2025-05-28 11:26 UTC, diggy128 commented on survey_link_base/models/survey_user_input.py
> +    origin_id = fields.Integer()
Maybe also add a reference field and add it to the user_input views to be able to go to the object that created the survey?

2025-05-28 11:26 UTC, diggy128 commented on survey_link_base/models/survey_link_mixin.py
> +    survey_count = fields.Integer(
survey_count here is ambiguous because it implies survey but computes survey answers, maybe rename field and compute method name?

2025-05-28 11:26 UTC, diggy128 commented on survey_link_base/models/survey_link_mixin.py
> +    def action_view_survey(self):
Same as above. action returns survey answers

2025-06-02 18:27 UTC, adasatorres commented
Hi, @diggy128 thank you for your review.

2025-06-13 22:28 UTC, edescalona approved these changes
LGTM

2025-06-14 08:33 UTC, pedrobaeza requested changes
The idea is OK, but it shouldn't include the partner link, at least in regular install (you may do it in demo, but `_partner_field` Python variable nor the method is not allowing to put this as demo data.

As is, it will choke with `partner_survey` module.

2025-06-14 11:58 UTC, adasatorres commented
Should I remove the integration with the partner? @pedrobaeza

2025-06-14 12:35 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2025-06-14 12:59 UTC, adasatorres commented
Sorry, @pedrobaeza i need refactor the tests.

2025-06-14 14:33 UTC, dreispt commented on survey_link_base/readme/USAGE.rst
> +which is useful if you want to use the get_share_link() method in a server action, etc.
I assume this is inaccurate now.
Since you'll be editing it, it would be nice to have an example on how to a developer can use this on a model, and how it looks like to the end user.

2025-06-14 14:53 UTC, adasatorres commented on survey_link_base/readme/USAGE.rst
> +which is useful if you want to use the get_share_link() method in a server action, etc.
Currently, the addon does not have a specific use beyond serving as a base for other modules.
I consider it unnecessary to include a Usage section; however, I have modified it and added a disclaimer accordingly.

2025-06-14 22:25 UTC, pedrobaeza commented
/ocabot merge nobump

2025-06-14 22:30 UTC, merged