[ADD] survey_description module
OCA/survey pull request #37
Opened 2020-06-16 16:59 UTC by remi-filament

Add description fields to surveys on backend (these fields are already present on the code but not displayed on backend)
[Odoo PR 52329](https://github.com/odoo/odoo/pull/52329) has been create to include this in Odoo code but since survey was refactored in V13, this may not be merged ever in Odoo code...

2020-08-13 09:07 UTC, apollet approved these changes

2020-08-25 21:22 UTC, skeller1 requested changes
LGTM :+1:
simple typo in docs (see review).
Also tested it with website_survey addon installed.

2020-08-25 21:22 UTC, skeller1 commented on survey_description/readme/DESCRIPTION.rst
> +Note: these fields are present in code, displayed on front-end for survey (when defined) but not displayed on back-end for user to fill.
back-end => backend

2020-10-21 14:52 UTC, remi-filament commented on survey_description/readme/DESCRIPTION.rst
> +Note: these fields are present in code, displayed on front-end for survey (when defined) but not displayed on back-end for user to fill.
Thank you Stephan, I just fixed it !

2020-10-26 19:02 UTC, skeller1 approved these changes

2021-01-19 06:18 UTC, Yoshiro009 approved these changes

2021-01-19 09:59 UTC, rousseldenis commented
/ocabot merge patch

2021-01-19 10:08 UTC, merged