[13.0][ADD] survey_sale_generation: New module 13.0
OCA/survey pull request #65
Opened 2022-12-30 15:56 UTC by chienandalu

cc @Tecnativa TT40983

2023-01-05 15:46 UTC, victoralmau requested changes
Good job, some comments related to functional review:

- Can you add tests to validate all steps?
- Add `sale_order_id` field in form view of `survey.user_input `for easy navigation.
- Add `survey_user_input_id` field in form view of `sale.order` for easy navigation.
- Question type: Multiple choice: only one answer: Use case is not correct (it generates as many lines as answers although only one can be selected).

2023-01-05 15:46 UTC, victoralmau commented on survey_sale_generation/models/survey_user_input.py
> +        ]
Maybe it would be a good idea to add lines (`order_line`) in `_prepare_quotation()` method directly. what do you think?

2023-01-09 08:40 UTC, chienandalu commented on survey_sale_generation/models/survey_user_input.py
> +        ]
I prefer to leave it split so other modules can hook directly in the future

2023-01-16 08:59 UTC, gurneyalex approved these changes

2023-01-16 08:59 UTC, gurneyalex commented
/ocabot merge nobump

2023-01-16 09:03 UTC, chienandalu commented
Thanks @gurneyalex . I was hoping to add some fixes. Can you abort?

2023-01-16 09:05 UTC, merged

2023-01-16 09:08 UTC, chienandalu commented
Nevermind. I'll do it in an extra PR :sweat_smile: