[13.0][ADD] survey_mail_result: New module
OCA/survey pull request #74
Opened 2023-03-07 13:16 UTC by chienandalu

cc @Tecnativa TT40981

2023-03-09 08:01 UTC, pedrobaeza requested changes
I haven't been able to test more, as sending invitations seems to not work, not sure if it's something due to this module.

2023-03-09 08:01 UTC, pedrobaeza commented on survey_result_mail/README.rst
> +email with the survey answers to the customer as soon as the questionary is completed.
```suggestion
email with the survey answers to the filler as soon as the questionary is completed.
```

2023-03-09 08:01 UTC, pedrobaeza commented on survey_result_mail/models/survey_survey.py
> +    send_survey_answers = fields.Boolean(
Avoid plurals in names:

```suggestion
    send_result_mail = fields.Boolean(
```

2023-03-09 08:01 UTC, pedrobaeza commented on survey_result_mail/views/survey_survey_views.xml
> +                <field name="send_survey_answers" />
You need to put a group to show the label:

```suggestion
                <group>
                    <field name="send_survey_answers" />
                </group>
```

![Selección_069](https://user-images.githubusercontent.com/7165771/223956498-5a95c6e1-6b9f-4bd7-942b-f5fcf92a8093.png)

Maybe this can go in the "Thank you message" page?

2023-03-09 08:01 UTC, pedrobaeza commented on survey_result_mail/reports/survey_answer_report.xml
> +    <report
Why putting this as a report. The idea is to have the answers in the mail body itself.

2023-03-09 08:01 UTC, pedrobaeza commented on survey_result_mail/models/survey_user_input.py
> +        for user_input in self.filtered("survey_id.send_survey_answers"):
We are only having the email address if the user is logged in. Isn't it? So maybe we should restrict it for now or have a way to indicate the email source (for example, one of the answers).

In fact, pressing "Test", this happens:

![Selección_070](https://user-images.githubusercontent.com/7165771/223958088-eca229f2-2894-4b8d-9ed9-7ecf1baeeff3.png)

2023-03-09 08:46 UTC, chienandalu commented on survey_result_mail/reports/survey_answer_report.xml
> +    <report
The aim is to be able to reuse the base results as much as possible and avoid falling into a jinja template hell (we don't have bootstrap, for example)

2023-03-09 08:46 UTC, chienandalu commented on survey_result_mail/models/survey_user_input.py
> +        for user_input in self.filtered("survey_id.send_survey_answers"):
Right, I should fix that.

2023-03-09 09:58 UTC, chienandalu commented on survey_result_mail/reports/survey_answer_report.xml
> +    <report
I explored how mass_mailing is doing it, but the conversion from bootstrap is made by the js of the editor, so we can't use that either.

2023-03-09 10:49 UTC, pedrobaeza commented on survey_result_mail/reports/survey_answer_report.xml
> +    <report
You can render a QWeb template as HTML, and inject it in the mail body.

2023-03-09 10:53 UTC, chienandalu commented on survey_result_mail/reports/survey_answer_report.xml
> +    <report
It would be without any style.

2023-03-09 11:03 UTC, pedrobaeza commented on survey_result_mail/reports/survey_answer_report.xml
> +    <report
Yes, but it's OK in this version, In v15, you can put styles in header.

2023-03-09 12:23 UTC, chienandalu commented on survey_result_mail/reports/survey_answer_report.xml
> +    <report
Maybe a minimized and cutoff version of bootstrap would do in that case... although we'll have to deal with mail client css limitations...

2023-03-09 16:56 UTC, pedrobaeza commented on survey_result_mail/reports/survey_answer_report.xml
> +    <report
Yes, but for now the most important thing is to have the content inside the mail, even in plain text, but it's not the case, as you can apply at least bold and so on.

2023-04-18 16:13 UTC, chienandalu commented on survey_result_mail/views/survey_survey_views.xml
> +                <field name="send_survey_answers" />
> Maybe this can go in the "Thank you message" page?

What do you mean?

2023-04-18 16:14 UTC, pedrobaeza commented on survey_result_mail/views/survey_survey_views.xml
> +                <field name="send_survey_answers" />
Move the field to the `<page>` in the notebook called "Thank you message"

2023-04-21 16:03 UTC, chienandalu commented on survey_result_mail/views/survey_survey_views.xml
> +                <field name="send_survey_answers" />
Looks like that view item doesn't exist anymore. I put it in the Questions section of the Options tab.

2023-04-21 16:03 UTC, chienandalu commented on survey_result_mail/models/survey_survey.py
> +    send_survey_answers = fields.Boolean(
done

2023-04-21 16:03 UTC, chienandalu commented on survey_result_mail/models/survey_user_input.py
> +        for user_input in self.filtered("survey_id.send_survey_answers"):
done

2023-04-21 16:04 UTC, chienandalu commented on survey_result_mail/README.rst
> +email with the survey answers to the customer as soon as the questionary is completed.
fixed

2023-04-25 16:12 UTC, chienandalu commented
Ready for review again

2023-07-05 19:25 UTC, pedrobaeza approved these changes
Can you please squash?

2023-07-06 06:28 UTC, chienandalu commented
Done. Isn't it possible to squash a PR commits via ocabot?

2023-07-08 17:16 UTC, pedrobaeza commented
> Done. Isn't it possible to squash a PR commits via ocabot?

I'm afraid not.

/ocabot merge nobump

2023-07-08 17:23 UTC, merged