[15.0][MIG] survey_resource_booking: Migration to version 15.0
OCA/survey pull request #75
Opened 2023-03-30 13:07 UTC by stefan-tecnativa

cc @Tecnativa TT41024

@chienandalu @ernestotejeda please review!

2023-03-30 14:01 UTC, ernestotejeda requested changes

2023-03-30 14:01 UTC, ernestotejeda commented on survey_resource_booking/tests/test_invite.py
> +        # wdb.set_trace()
```suggestion
```

2023-03-30 14:41 UTC, stefan-tecnativa commented on survey_resource_booking/tests/test_invite.py
> +        # wdb.set_trace()
Ups, I forgot that. Thanks.

2023-03-30 14:59 UTC, ernestotejeda approved these changes

2023-04-07 19:11 UTC, pedrobaeza commented
/ocabot migration survey_resource_booking

2023-04-07 19:17 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2023-04-07 19:21 UTC, merged