[MIG] partner_survey: Migration to 16.0
OCA/survey pull request #87
Opened 2023-06-26 19:22 UTC by matiasperalta1

2023-08-11 15:36 UTC, pieterdemil commented
Would be nice if this becomes available for version 16.0

2023-08-11 15:48 UTC, pedrobaeza commented
Help reviewing it: https://odoo-community.org/page/review

2023-08-11 15:49 UTC, pedrobaeza commented
/ocabot migration partner_survey

2023-11-07 10:11 UTC, flotho commented
ping @matiasperalta1 , is it possible to push a little commit to trigger runboat ?

2024-07-16 11:47 UTC, Deriman-Alonso approved these changes
LGTM👍, functional test and code review

2024-07-22 16:45 UTC, curonny approved these changes

2024-07-22 20:43 UTC, flotho commented
cc @DorainMAG @JulienMartinez

2024-07-23 06:43 UTC, DorianMAG commented
@matiasperalta1 
Can you rebase plz?
Code review, seems to be good, but can't test in runboat.
Regards

2024-12-12 13:43 UTC, arielbarreiros96 commented
@matiasperalta1 can you consider to include this feature back before the merge https://github.com/OCA/survey/pull/138

2025-04-01 04:45 UTC, kobros-tech requested changes
Can we add merged commits like this one:
https://github.com/OCA/survey/pull/138/commits/6e096c4b669eaef8a3c3372aae9a91984b330003

2025-04-26 18:37 UTC, kobros-tech commented
@matiasperalta1 

shall we merge all requested updates for getting this module merged or I can open a new PR if you are busy?

2025-04-27 09:07 UTC, pedrobaeza commented
@kobros-tech I think you can supersede the PR and propose a new one starting from this one.

2025-04-29 06:25 UTC, closed without merging